### ISSUE TITLE
Twig comments

### ISSUE THREAD

**Issue by nilshendriks** [YussufSassi/zed-twig#3]
Twig comments dont seem to work. Only get HTML comments.

{# This will be a comment #}

{# This will be a 
multi-line
comment. 
#}

**Comment by nilshendriks** [comment]
Great! How to update the extension in Zed? Re-install? I do not see a newer version there.

**Comment by sweetroll** [comment]
It does work by uninstalling the HTML extension but then we lose syntax highlighting etc. Can we get the twig extension to take precedence in twig files?

**Comment by mynetx** [comment]
It will work after zed-industries/zed#29716

**Comment by FabianKostenzer** [comment]
@mynetx 
It does still not work. Toggling comments inside any HTML element still results in HTML comments. Even if the line to comment only consists of twig code (for, if, set etc.)

It only works outside HTML elements (on the root level of every twig-file).

Example:

```
{% set foo = 'bar' %}
    
<div>
    {% set bar = 'foo' %}
</div>
```
If I try to comment both set-statements, it will result in the following code:

```
{# {% set foo = 'bar' %} #}
    
<div>
    <!--{% set bar = 'foo' %}-->
</div>
```
The first set-statement correctly got commented with twig comments.
The second set-statement inside the HTML element got commented with HTML comments.

**Comment by ghisleouf** [comment]
Hello !

Exact same behavior as @FabianKostenzer !
